name: Regression Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pytest pytest-html pytest-cov

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD:$PWD/src" >> $GITHUB_ENV

      - name: Run regression (HTML + Coverage)
        run: |
          mkdir -p reports
          pytest \
            --html=reports/report.html --self-contained-html \
            --cov=src --cov-report=term-missing \
            --cov-report=xml:coverage.xml \
            --cov-report=html:coverage_html \
            --cov-fail-under=85

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/report.html

      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage_html
